# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgmenu',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
