# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanageapp', '0005_auto_20200415_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LunchAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='MealAgreement',
        ),
    ]
