# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanageapp', '0009_auto_20200416_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='user_image',
            field=models.ImageField(default=0, upload_to='pgfoodmanagement/product_image'),
            preserve_default=False,
        ),
    ]
