# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanageapp', '0012_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='user_image',
        ),
    ]
